### PR TITLE
feat: add image-charts.com

### PR DESCRIPTION
**Pull request by FGRibreau**

### CODE REVIEW

**Comment by fiatjaf** [comment]
Hey, this looks awesome. However, the site looks a bit confusing and has some broken links and images. Is it something you just launched and is improving?

**Comment by fiatjaf** [comment]
How do I create a QR code? I can't find anything about that in the docs. Is there a way to create a QR code with stuff written on it?

**Comment by FGRibreau** [comment]
Hello @fiatjaf !

> However, the site looks a bit confusing

Interesting feedback, what is confusing?

> has some broken links and images

Could you please tell me where so we can fix this?

> How do I create a QR code? 

Yes, it's currently not shared publicly on our documentation because it's in beta, it's the same as [Google Image-Charts](https://developers.google.com/chart/infographics/docs/qr_codes) 

```
https://image-charts.com/chart?cht=qr&chs=100x100&chl=hello%20world
```

**Comment by fiatjaf** [comment]
2019-03-13-181029_1896x913_scrot

"Pricing" section has only: "You are a bootstrapping a startup 🦄 or in education 🎓? Need a discount 💸? Contact us!"

The landing page doesn't make it clear that "1 url = 1 chart" means writing an URL with all the data you need in a loginless way. It could as well be register->create chart on dashboard->get URL.

**Comment by FGRibreau** [comment]
Hum either you had an issue with your connection or there is something else. 
Where are you located? What browser do you use?

> The landing page doesn't make it clear that "1 url = 1 chart" means writing an URL with all the data you need in a loginless way.

We are just doing it the same way as https://developers.google.com/chart/image/

**Pull request closed without merging**
